# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zz1au/projects/WebChat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zz1au/projects/WebChat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz1au/projects/WebChat/CMakeFiles /home/zz1au/projects/WebChat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zz1au/projects/WebChat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sqlite3

# Build rule for target.
sqlite3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlite3
.PHONY : sqlite3

# fast build rule for target.
sqlite3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/build
.PHONY : sqlite3/fast

#=============================================================================
# Target rules for targets named WebChat

# Build rule for target.
WebChat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebChat
.PHONY : WebChat

# fast build rule for target.
WebChat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/build
.PHONY : WebChat/fast

Http/http_handle.o: Http/http_handle.cpp.o
.PHONY : Http/http_handle.o

# target to build an object file
Http/http_handle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Http/http_handle.cpp.o
.PHONY : Http/http_handle.cpp.o

Http/http_handle.i: Http/http_handle.cpp.i
.PHONY : Http/http_handle.i

# target to preprocess a source file
Http/http_handle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Http/http_handle.cpp.i
.PHONY : Http/http_handle.cpp.i

Http/http_handle.s: Http/http_handle.cpp.s
.PHONY : Http/http_handle.s

# target to generate assembly for a file
Http/http_handle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Http/http_handle.cpp.s
.PHONY : Http/http_handle.cpp.s

Http/http_msg.o: Http/http_msg.cpp.o
.PHONY : Http/http_msg.o

# target to build an object file
Http/http_msg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Http/http_msg.cpp.o
.PHONY : Http/http_msg.cpp.o

Http/http_msg.i: Http/http_msg.cpp.i
.PHONY : Http/http_msg.i

# target to preprocess a source file
Http/http_msg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Http/http_msg.cpp.i
.PHONY : Http/http_msg.cpp.i

Http/http_msg.s: Http/http_msg.cpp.s
.PHONY : Http/http_msg.s

# target to generate assembly for a file
Http/http_msg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Http/http_msg.cpp.s
.PHONY : Http/http_msg.cpp.s

SQLite/SQLhandle.o: SQLite/SQLhandle.cpp.o
.PHONY : SQLite/SQLhandle.o

# target to build an object file
SQLite/SQLhandle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/SQLite/SQLhandle.cpp.o
.PHONY : SQLite/SQLhandle.cpp.o

SQLite/SQLhandle.i: SQLite/SQLhandle.cpp.i
.PHONY : SQLite/SQLhandle.i

# target to preprocess a source file
SQLite/SQLhandle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/SQLite/SQLhandle.cpp.i
.PHONY : SQLite/SQLhandle.cpp.i

SQLite/SQLhandle.s: SQLite/SQLhandle.cpp.s
.PHONY : SQLite/SQLhandle.s

# target to generate assembly for a file
SQLite/SQLhandle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/SQLite/SQLhandle.cpp.s
.PHONY : SQLite/SQLhandle.cpp.s

Server/Chatserver.o: Server/Chatserver.cpp.o
.PHONY : Server/Chatserver.o

# target to build an object file
Server/Chatserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Server/Chatserver.cpp.o
.PHONY : Server/Chatserver.cpp.o

Server/Chatserver.i: Server/Chatserver.cpp.i
.PHONY : Server/Chatserver.i

# target to preprocess a source file
Server/Chatserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Server/Chatserver.cpp.i
.PHONY : Server/Chatserver.cpp.i

Server/Chatserver.s: Server/Chatserver.cpp.s
.PHONY : Server/Chatserver.s

# target to generate assembly for a file
Server/Chatserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Server/Chatserver.cpp.s
.PHONY : Server/Chatserver.cpp.s

Socket/Socket.o: Socket/Socket.cpp.o
.PHONY : Socket/Socket.o

# target to build an object file
Socket/Socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Socket/Socket.cpp.o
.PHONY : Socket/Socket.cpp.o

Socket/Socket.i: Socket/Socket.cpp.i
.PHONY : Socket/Socket.i

# target to preprocess a source file
Socket/Socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Socket/Socket.cpp.i
.PHONY : Socket/Socket.cpp.i

Socket/Socket.s: Socket/Socket.cpp.s
.PHONY : Socket/Socket.s

# target to generate assembly for a file
Socket/Socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Socket/Socket.cpp.s
.PHONY : Socket/Socket.cpp.s

Utility/ChatRoomInfo.o: Utility/ChatRoomInfo.cpp.o
.PHONY : Utility/ChatRoomInfo.o

# target to build an object file
Utility/ChatRoomInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/ChatRoomInfo.cpp.o
.PHONY : Utility/ChatRoomInfo.cpp.o

Utility/ChatRoomInfo.i: Utility/ChatRoomInfo.cpp.i
.PHONY : Utility/ChatRoomInfo.i

# target to preprocess a source file
Utility/ChatRoomInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/ChatRoomInfo.cpp.i
.PHONY : Utility/ChatRoomInfo.cpp.i

Utility/ChatRoomInfo.s: Utility/ChatRoomInfo.cpp.s
.PHONY : Utility/ChatRoomInfo.s

# target to generate assembly for a file
Utility/ChatRoomInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/ChatRoomInfo.cpp.s
.PHONY : Utility/ChatRoomInfo.cpp.s

Utility/Jsonhandle.o: Utility/Jsonhandle.cpp.o
.PHONY : Utility/Jsonhandle.o

# target to build an object file
Utility/Jsonhandle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/Jsonhandle.cpp.o
.PHONY : Utility/Jsonhandle.cpp.o

Utility/Jsonhandle.i: Utility/Jsonhandle.cpp.i
.PHONY : Utility/Jsonhandle.i

# target to preprocess a source file
Utility/Jsonhandle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/Jsonhandle.cpp.i
.PHONY : Utility/Jsonhandle.cpp.i

Utility/Jsonhandle.s: Utility/Jsonhandle.cpp.s
.PHONY : Utility/Jsonhandle.s

# target to generate assembly for a file
Utility/Jsonhandle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/Jsonhandle.cpp.s
.PHONY : Utility/Jsonhandle.cpp.s

Utility/MsgInfo.o: Utility/MsgInfo.cpp.o
.PHONY : Utility/MsgInfo.o

# target to build an object file
Utility/MsgInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/MsgInfo.cpp.o
.PHONY : Utility/MsgInfo.cpp.o

Utility/MsgInfo.i: Utility/MsgInfo.cpp.i
.PHONY : Utility/MsgInfo.i

# target to preprocess a source file
Utility/MsgInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/MsgInfo.cpp.i
.PHONY : Utility/MsgInfo.cpp.i

Utility/MsgInfo.s: Utility/MsgInfo.cpp.s
.PHONY : Utility/MsgInfo.s

# target to generate assembly for a file
Utility/MsgInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/MsgInfo.cpp.s
.PHONY : Utility/MsgInfo.cpp.s

Utility/TimeH.o: Utility/TimeH.cpp.o
.PHONY : Utility/TimeH.o

# target to build an object file
Utility/TimeH.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/TimeH.cpp.o
.PHONY : Utility/TimeH.cpp.o

Utility/TimeH.i: Utility/TimeH.cpp.i
.PHONY : Utility/TimeH.i

# target to preprocess a source file
Utility/TimeH.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/TimeH.cpp.i
.PHONY : Utility/TimeH.cpp.i

Utility/TimeH.s: Utility/TimeH.cpp.s
.PHONY : Utility/TimeH.s

# target to generate assembly for a file
Utility/TimeH.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/TimeH.cpp.s
.PHONY : Utility/TimeH.cpp.s

Utility/UserInfo.o: Utility/UserInfo.cpp.o
.PHONY : Utility/UserInfo.o

# target to build an object file
Utility/UserInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/UserInfo.cpp.o
.PHONY : Utility/UserInfo.cpp.o

Utility/UserInfo.i: Utility/UserInfo.cpp.i
.PHONY : Utility/UserInfo.i

# target to preprocess a source file
Utility/UserInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/UserInfo.cpp.i
.PHONY : Utility/UserInfo.cpp.i

Utility/UserInfo.s: Utility/UserInfo.cpp.s
.PHONY : Utility/UserInfo.s

# target to generate assembly for a file
Utility/UserInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebChat.dir/build.make CMakeFiles/WebChat.dir/Utility/UserInfo.cpp.s
.PHONY : Utility/UserInfo.cpp.s

sqlite3/sqlite3.o: sqlite3/sqlite3.c.o
.PHONY : sqlite3/sqlite3.o

# target to build an object file
sqlite3/sqlite3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/sqlite3/sqlite3.c.o
.PHONY : sqlite3/sqlite3.c.o

sqlite3/sqlite3.i: sqlite3/sqlite3.c.i
.PHONY : sqlite3/sqlite3.i

# target to preprocess a source file
sqlite3/sqlite3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/sqlite3/sqlite3.c.i
.PHONY : sqlite3/sqlite3.c.i

sqlite3/sqlite3.s: sqlite3/sqlite3.c.s
.PHONY : sqlite3/sqlite3.s

# target to generate assembly for a file
sqlite3/sqlite3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/sqlite3/sqlite3.c.s
.PHONY : sqlite3/sqlite3.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... WebChat"
	@echo "... sqlite3"
	@echo "... Http/http_handle.o"
	@echo "... Http/http_handle.i"
	@echo "... Http/http_handle.s"
	@echo "... Http/http_msg.o"
	@echo "... Http/http_msg.i"
	@echo "... Http/http_msg.s"
	@echo "... SQLite/SQLhandle.o"
	@echo "... SQLite/SQLhandle.i"
	@echo "... SQLite/SQLhandle.s"
	@echo "... Server/Chatserver.o"
	@echo "... Server/Chatserver.i"
	@echo "... Server/Chatserver.s"
	@echo "... Socket/Socket.o"
	@echo "... Socket/Socket.i"
	@echo "... Socket/Socket.s"
	@echo "... Utility/ChatRoomInfo.o"
	@echo "... Utility/ChatRoomInfo.i"
	@echo "... Utility/ChatRoomInfo.s"
	@echo "... Utility/Jsonhandle.o"
	@echo "... Utility/Jsonhandle.i"
	@echo "... Utility/Jsonhandle.s"
	@echo "... Utility/MsgInfo.o"
	@echo "... Utility/MsgInfo.i"
	@echo "... Utility/MsgInfo.s"
	@echo "... Utility/TimeH.o"
	@echo "... Utility/TimeH.i"
	@echo "... Utility/TimeH.s"
	@echo "... Utility/UserInfo.o"
	@echo "... Utility/UserInfo.i"
	@echo "... Utility/UserInfo.s"
	@echo "... sqlite3/sqlite3.o"
	@echo "... sqlite3/sqlite3.i"
	@echo "... sqlite3/sqlite3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

